#!/usr/bin/env bash
set -euo pipefail

# ─── Copilot Dotfiles Installer ─────────────────────────────────────────────
# Doctor mode: checks → reports → offers fixes.
# Generated by copilot-sync from claude-dotfiles.
#
# Usage:
#   ./install.sh              # interactive doctor mode
#   ./install.sh --dry-run    # show what would change
#   ./install.sh --force      # auto-fix without prompting
#   ./install.sh --uninstall  # remove symlinks only

DOTFILES_DIR="$(cd "$(dirname "$0")" && pwd)"
COPILOT_DIR="$HOME/.copilot"
MCP_CONFIG="$COPILOT_DIR/mcp-config.json"

# ─── Options ─────────────────────────────────────────────────────────────────
DRY_RUN=false
FORCE=false
UNINSTALL=false
for arg in "$@"; do
  case "$arg" in
    --dry-run)   DRY_RUN=true ;;
    --force)     FORCE=true ;;
    --uninstall) UNINSTALL=true ;;
  esac
done

# ─── Logging ─────────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[0;33m'; CYAN='\033[0;36m'; NC='\033[0m'
OK="${GREEN}OK${NC}"; WARN="${YELLOW}WARN${NC}"; FAIL="${RED}FAIL${NC}"; FIX="${CYAN}FIX${NC}"
CHECKS=0; PASSED=0; FIXED=0; FAILED=0

log_ok()   { ((CHECKS++)) || true; ((PASSED++)) || true; echo -e "  [$OK]   $1"; }
log_warn() { ((CHECKS++)) || true; echo -e "  [$WARN] $1"; }
log_fail() { ((CHECKS++)) || true; ((FAILED++)) || true; echo -e "  [$FAIL] $1"; }
log_fix()  { ((FIXED++)) || true; echo -e "  [$FIX]  $1"; }

prompt_fix() {
  if $FORCE; then return 0; fi
  if $DRY_RUN; then echo "  [dry-run] would fix: $1"; return 1; fi
  read -rp "  Fix: $1? [y/N] " answer
  [[ "$answer" =~ ^[Yy] ]]
}

# ─── Uninstall ───────────────────────────────────────────────────────────────
if $UNINSTALL; then
  echo "Removing copilot-dotfiles symlinks..."
  rm -f "$COPILOT_DIR/copilot-instructions.md"
  rm -f "$COPILOT_DIR/skills"
  rm -f "$COPILOT_DIR/agents"
  echo "Done. Config and MCP registration left intact."
  exit 0
fi

# ─── Phase 1: Prerequisites ─────────────────────────────────────────────────
echo ""
echo "Phase 1: Prerequisites"
echo "─────────────────────"

for cmd in node git copilot just gh; do
  if command -v "$cmd" &>/dev/null; then
    log_ok "$cmd found: $(command -v "$cmd")"
  else
    log_fail "$cmd not found"
    case "$cmd" in
      node)    echo "         Install: https://nodejs.org/" ;;
      copilot) echo "         Install: npm install -g @github/copilot" ;;
      just)    echo "         Install: cargo install just OR https://just.systems/man/en/installation.html" ;;
      gh)      echo "         Install: https://cli.github.com/" ;;
    esac
  fi
done

# ─── Phase 2: Directory Structure ───────────────────────────────────────────
echo ""
echo "Phase 2: Directory Structure"
echo "────────────────────────────"

mkdir -p "$COPILOT_DIR"
log_ok "~/.copilot/ exists"

# ─── Phase 3: Symlinks ──────────────────────────────────────────────────────
echo ""
echo "Phase 3: Symlinks"
echo "──────────────────"

declare -A SYMLINKS=(
  ["$COPILOT_DIR/copilot-instructions.md"]="$DOTFILES_DIR/copilot-instructions.md"
  ["$COPILOT_DIR/skills"]="$DOTFILES_DIR/skills"
  ["$COPILOT_DIR/agents"]="$DOTFILES_DIR/agents"
)

for target in "${!SYMLINKS[@]}"; do
  src="${SYMLINKS[$target]}"
  if [ -L "$target" ] && [ "$(readlink "$target")" = "$src" ]; then
    log_ok "$(basename "$target") → $src"
  elif [ -e "$target" ] && [ ! -L "$target" ]; then
    log_warn "$(basename "$target") exists but is not a symlink"
    if prompt_fix "Replace with symlink to $src"; then
      rm -rf "$target"
      ln -s "$src" "$target"
      log_fix "Replaced with symlink"
    fi
  else
    log_warn "$(basename "$target") not linked"
    if prompt_fix "Create symlink to $src"; then
      ln -s "$src" "$target"
      log_fix "Created symlink"
    fi
  fi
done

# ─── Phase 4: Config Merge ──────────────────────────────────────────────────
echo ""
echo "Phase 4: Config"
echo "────────────────"

if [ -f "$COPILOT_DIR/config.json" ]; then
  log_ok "config.json exists (not overwriting — merge manually if needed)"
  echo "         Source: $DOTFILES_DIR/config.json"
else
  log_warn "config.json missing"
  if prompt_fix "Copy config.json to ~/.copilot/"; then
    cp "$DOTFILES_DIR/config.json" "$COPILOT_DIR/config.json"
    log_fix "Copied config.json"
  fi
fi

# ─── Phase 5: MCP Registration ──────────────────────────────────────────────
echo ""
echo "Phase 5: MCP Servers"
echo "─────────────────────"

if [ -f "$MCP_CONFIG" ]; then
  if grep -q "session-context" "$MCP_CONFIG"; then
    log_ok "session-context registered in mcp-config.json"
  else
    log_warn "session-context not in mcp-config.json"
    if prompt_fix "Merge MCP config"; then
      sed "s|\\./mcp/|$DOTFILES_DIR/mcp/|g" "$DOTFILES_DIR/mcp-config.json" > "$MCP_CONFIG"
      log_fix "Copied mcp-config.json (review for manual merge if you had custom servers)"
    fi
  fi
else
  log_warn "mcp-config.json missing"
  if prompt_fix "Create mcp-config.json"; then
    sed "s|\\./mcp/|$DOTFILES_DIR/mcp/|g" "$DOTFILES_DIR/mcp-config.json" > "$MCP_CONFIG"
    log_fix "Created mcp-config.json"
  fi
fi

# ─── Phase 6: Plugins ───────────────────────────────────────────────────────
echo ""
echo "Phase 6: Plugins"
echo "──────────────────"

if command -v copilot &>/dev/null; then
    # superpowers
    copilot plugin marketplace add obra/superpowers-marketplace 2>/dev/null || true
    copilot plugin install superpowers-marketplace/superpowers 2>/dev/null || log_warn "superpowers plugin install failed — install manually"
    # playwright (CLI tool)
    npm install -g @playwright/cli || log_warn "playwright install failed — install manually"
    log_ok "Plugin installation complete"
else
    log_warn "copilot CLI not found — skipping plugin installation"
fi

# ─── Phase 7: Machine Identity ──────────────────────────────────────────────
echo ""
echo "Phase 7: Machine Identity"
echo "──────────────────────────"

if [ -f "$HOME/.machine-id" ]; then
  log_ok "~/.machine-id: $(cat "$HOME/.machine-id")"
else
  log_warn "~/.machine-id not found (shared with claude-dotfiles)"
  echo "         Create it: echo 'machine-name' > ~/.machine-id"
fi

# ─── Phase 8: MCP Server Build ──────────────────────────────────────────────
echo ""
echo "Phase 8: MCP Server Build"
echo "──────────────────────────"

MCP_DIR="$DOTFILES_DIR/mcp/session-context"
if [ -d "$MCP_DIR/dist" ]; then
  log_ok "session-context MCP server built"
else
  log_warn "session-context MCP server not built"
  if prompt_fix "Build MCP server (npm install && npm run build)"; then
    (cd "$MCP_DIR" && npm install && npm run build)
    log_fix "MCP server built"
  fi
fi

# ─── Phase 9: Python Tooling ────────────────────────────────────────────────
echo ""
echo "Phase 9: Python Tooling (for document generation)"
echo "──────────────────────────────────────────────────"

if command -v python3 &>/dev/null; then
  log_ok "python3 found: $(python3 --version)"

  # Check for required packages
  MISSING_PKGS=()
  python3 -c "import pptx" 2>/dev/null || MISSING_PKGS+=("python-pptx")
  python3 -c "import docx" 2>/dev/null || MISSING_PKGS+=("python-docx")

  if [ ${#MISSING_PKGS[@]} -eq 0 ]; then
    log_ok "python-pptx and python-docx installed"
  else
    log_warn "Missing Python packages: ${MISSING_PKGS[*]}"
    if prompt_fix "Install Python dependencies (pip install -r requirements.txt)"; then
      pip install -r "$DOTFILES_DIR/requirements.txt"
      log_fix "Installed Python dependencies"
    fi
  fi
else
  log_warn "python3 not found - document generation skills won't work"
  echo "         Install: https://www.python.org/downloads/"
fi

# ─── Summary ─────────────────────────────────────────────────────────────────
echo ""
echo "════════════════════════════"
echo -e "  Checks: $CHECKS  Passed: $PASSED  Fixed: $FIXED  Failed: $FAILED"
echo "════════════════════════════"

if [ "$FAILED" -gt 0 ]; then
  echo -e "${RED}Some checks failed. Fix the issues above and re-run.${NC}"
  exit 1
else
  echo -e "${GREEN}All checks passed.${NC}"
fi
